#!/usr/bin/env python
"""Assert every tier x energy-axis number in the manuscript against the JSON
generated by scripts/analyze_tier_energy_gating.py.

Why this exists: the published version of §3.12 was written by hand. When two
fold-neutral interface systems entered the benchmark, its contingency cells
went stale while its stated denominator was updated -- the section ended up
mixing values from two vintages, and one cell reproduced under no population
definition and no table vintage at all. No existing audit asserted any literal
from that section, so the drift was silent.

Contract: every number in §3.12 must be derivable from
reference_outputs/COMAVI_tier_energy_gating.json. Run the analysis script
first; this asserts the prose agrees with it.

Checks run in both directions:
  (a) every generated value that the prose quotes must appear in the prose;
  (b) every retired literal from the stale version must be absent.
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from audit_match import check_literal, weak_needle  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
MS = REPO / "docs" / "COMAVI_manuscript_v22.md"
JSON = REPO / "reference_outputs" / "COMAVI_tier_energy_gating.json"
TC = REPO / "reference_outputs" / "COMAVI_tier_construction.json"
SILENT = "structurally_silent"


def section(text, start_marker, end_marker):
    i = text.index(start_marker)
    j = text.index(end_marker, i)
    return text[i:j]


def flat(s):
    """Collapse all whitespace to single spaces.

    The manuscript is hard-wrapped, so a literal like '47 tier-carrying' is
    split across a line break in the source. Matching on unnormalised text
    produces spurious failures that tempt one to edit the paper to satisfy
    the audit -- exactly backwards.
    """
    return re.sub(r"\s+", " ", s)


def main():
    if not JSON.exists():
        sys.exit(f"missing {JSON.relative_to(REPO)} -- run analyze_tier_energy_gating.py first")
    if not MS.exists():
        print(f"[SKIP] {MS.relative_to(REPO)} is not present in this checkout.")
        print("       The manuscript is withheld until preprint/submission, so this")
        print("       audit has nothing to check. Every value it would verify is")
        print("       regenerated by scripts/analyze_tier_energy_gating.py and")
        print("       scripts/verify_tier_construction.py, which do not read prose.")
        sys.exit(0)
    j = json.loads(JSON.read_text())
    text = MS.read_text()
    sec = section(text, "### 3.12 ", "### 3.13 ")

    # The specificity-gain bootstrap lives in tier_construction.json, not the
    # gating output. It was ungated in prose until now, which is how a stale
    # 4,000-draw bound (+0.233) survived in §3.12 after the estimator moved to
    # 20,000 draws (+0.24). Gate the reportable 2-dp interval, never the 3-dp raw.
    sg = json.loads(TC.read_text())["specificity_gain"]
    m = j["marginal_tier_screen"]
    c = j["classifier"]
    sw = j["sweep"]
    bh = j["bh"]
    smc = j["stratum_mc"]

    def pct(x):
        return f"{x:.3f}".rstrip("0").rstrip(".")

    required = [
        # --- population ---
        (f"Across the {j['population_n']} tier-carrying variants", "population size"),
        # --- marginal screen: the section's headline ---
        (f"{m['strong_structural']} structurally-mechanistic", "marginal structural count"),
        # The zero cell is the section's core claim, so it must be gated on the
        # sentence that asserts it. A bare "0" needle matched inside every
        # decimal in the section and constrained nothing.
        (f"none of the {m['weak_n']} Tier 3\u20134 variants has a structural mechanism"
         if m["weak_structural"] == 0 else
         f"{m['weak_structural']} of the {m['weak_n']} Tier 3\u20134 variants",
         "marginal weak-tier structural count (zero cell)"),
        (f"{m['strong_structural']}/{m['strong_structural']}", "recall as fraction"),
        (f"{m['sensitivity_ci'][0]:.3f}", "recall CI lower"),
        (f"{m['specificity']:.3f}", "specificity"),
        (f"{m['strong_structural']}/{m['strong_n']}", "specificity as fraction"),
        (f"{m['specificity_ci'][0]:.3f}", "specificity CI lower"),
        (f"{m['specificity_ci'][1]:.3f}", "specificity CI upper"),
        (f"{m['n_systems_in_weak_cell']} of the {j['population_systems']} systems", "weak-cell system coverage"),
        (f"{m['n_systems_with_both_strata']} systems carry both", "both-strata system count"),
        (f"p = {m['within_system_permutation_p']:.4f}", "within-system permutation p"),
        (f"[{sg['reference_t25_cluster_bootstrap_ci'][0]:.2f}, "
         f"+{sg['reference_t25_cluster_bootstrap_ci'][1]:.2f}]",
         "specificity-gain cluster bootstrap CI (2 dp)"),
        (f"{sg['fraction_resamples_no_gain_pct_reportable']}% of resamples",
         "fraction of resamples with no gain"),
        (f"+{m['cluster_bootstrap_rate_diff_ci'][0]:.3f}", "cluster bootstrap CI lower"),
        (f"+{m['cluster_bootstrap_rate_diff_ci'][1]:.3f}", "cluster bootstrap CI upper"),
        # --- recall decomposition ---
        (f"{m['structural_by_class']['ppi_destab_mechanism']} of the {m['strong_structural']}", "interface-bonus share"),
        (f"remaining {m['non_ppi_structural_n']} reach Tier", "non-PPI structural count"),
        (f"{m['structural_by_class']['mixed_structural']} mixed-structural", "mixed-structural count"),
        (f"{m['fold_mechanism_n']} fold-mechanism", "fold-mechanism count"),
        # --- stratified sweep table ---
        *[(f"{v['firing']['strong_structural']}/{v['firing']['strong_n']} vs "
           f"{v['firing']['weak_structural']}/{v['firing']['weak_n']}", f"sweep cells {t}")
          for t, v in sw.items()],
        *[(f"{v['firing']['fisher_p']:.4f}", f"sweep fisher p {t}") for t, v in sw.items()],
        (f"{bh['firing_t25']['p_adj']:.3f}", "BH-adjusted canonical"),
        # --- stratum mechanism consistency ---
        (f"{smc['convergent_all']['mc']:.3f}", "convergent stratum MC"),
        (f"{smc['convergent_structural_gt']['n']} ground-truth-structural", "convergent structural n"),
        (f"{smc['convergent_structural_gt']['mc']:.3f}", "convergent structural MC"),
        (f"{smc['convergent_silent_gt']['mc']:.3f}", "convergent silent MC"),
        *[(v, f"convergent silent variant {v}") for v in smc["convergent_silent_gt"]["variants"]],
        # --- classifier ---
        (f"{c['n']} variants carrying both", "classifier population"),
        (f"{c['n_pathogenic']} pathogenic, {c['n_benign']} benign", "classifier label split"),
        (f"{c['n_systems']} systems", "classifier system count"),
        (f"AUC {c['auc_energy']:.3f}", "energy AUC"),
        (f"{c['auc_tier']:.3f}", "tier AUC"),
        (f"{abs(c['auc_delta_cluster_bootstrap_ci'][0]):.3f}", "AUC delta CI lower"),
        (f"{c['auc_delta_cluster_bootstrap_ci'][1]:.3f}", "AUC delta CI upper"),
        (f"{abs(c['spearman_tier_vs_energy']):.3f}", "tier-energy Spearman"),
    ]

    # --- construction verification (scripts/verify_tier_construction.py) -----
    # These lock the corrected circularity claim. The section previously argued
    # from mechanism CLASS that the interface bonus accounts for 6 of 17; the
    # component recomputation shows it reaches 15 of 17. If that recomputation
    # ever stops reproducing the shipped tiers, the claim is unsupported.
    if TC.exists():
        tc = json.loads(TC.read_text())
        ib, ab = tc["interface_bonus_reach"], tc["screen_interface_bonus_zeroed"]
        assert tc["reimplementation_fidelity"] == f"{tc['population_n']}/{tc['population_n']}", (
            "verify_tier_construction.py no longer reproduces the shipped tier; "
            "§3.12's ablation claim is unsupported until it does"
        )
        required += [
            (f"{ib['structural_with_bonus']} of the {ib['structural_total']} structural variants "
             f"receive a nonzero", "corrected interface-bonus reach"),
            (f"{ib['by_class']['mixed_structural']} mixed-structural", "bonus reach by class (mixed)"),
            (f"{ib['by_class']['ppi_destab_mechanism']} binding-only", "bonus reach by class (binding)"),
            (f"{ib['by_class']['fold_mechanism']} fold-mechanism", "bonus reach by class (fold)"),
            *[(v, f"structural variant without interface bonus: {v}")
              for v in ib["structural_without_bonus"]],
            (f"{ab['strong_structural']}/{ab['strong_structural'] + ab['weak_structural']} = "
             f"{ab['sensitivity']:.3f}", "ablated sensitivity"),
            (f"{ab['specificity']:.3f}", "ablated specificity"),
            (f"Fisher p = {ab['fisher_p']:.4f}", "ablated Fisher p"),
            (f"p = {ab['within_system_permutation_p']:.3f}", "ablated permutation p"),
            # Every demoted variant must be named, silent ones included. The
            # earlier version of this audit excluded silent demotions, which is
            # precisely how the manuscript came to report three demotions when
            # the ablation produces four: the omitted variant (CALM1 D96V) is
            # silent, and its single demotion is the whole apparent specificity
            # gain. Excluding that class made the omission unauditable.
            *[(r["variant"], f"variant demoted by ablation ({r['expected_mech_class']}): {r['variant']}")
              for r in tc["all_demotions"]],
        ]
        # Evidence-restricted sensitivity views. Gated CONDITIONALLY on which
        # quantifier the prose commits to, because "restrict to E1-E3" has two
        # non-equivalent readings that differ by 15 variants (see the semantics
        # note in verify_tier_construction.py). A draft saying "all committed
        # axes" must quote the ALL row; one saying "at least one axis" the ANY
        # row. Hardcoding either would fail the other legitimate wording.
        # Each entry: (ALL-quantifier trigger, ANY-quantifier trigger, keys).
        # BOTH triggers must be specific to a restricted-view sentence. An earlier
        # version keyed the ANY branch on the bare word "committed", which occurs
        # throughout the evidence section, so the gate demanded restricted-view
        # numbers from a manuscript that never claimed the view at all.
        erv = tc.get("evidence_restricted_views", {})
        for all_trig, any_trig, allkey, anykey in [
            ("committed axes are all", "at least one committed axis",
             "all_axes_E1_E3", "any_axis_E1_E3"),
            ("every committed axis to be direct or coupled",
             "any committed axis is direct or coupled",
             "all_axes_direct_or_coupled", "any_axis_direct_or_coupled"),
        ]:
            # Trigger on `sec`, not `text`: required literals are searched inside
            # §3.12, so a trigger found elsewhere in the paper would demand
            # numbers in a section that never makes the claim.
            key = (allkey if all_trig in sec
                   else anykey if any_trig in sec else None)
            if key and key in erv:
                v = erv[key]
                required += [
                    (f"n = {v['n']}", f"{key} cohort size"),
                    (f"{v['specificity']:.3f}", f"{key} specificity"),
                ]
        # A "context-representable" view is not computable from shipped data, so
        # no number may be attributed to it. These literals were quoted in a
        # circulated draft; they are ungated by construction and must not appear.
        ungated_context_view = [
            ("n = 45", "ungated context-representable cohort size"),
            ("0.571", "ungated context-representable specificity"),
        ]
        # The sensitivity-invariance identity must never be reported as a finding.
        forbidden_extra = [
            ("without losing sensitivity", "sensitivity identity stated as an empirical result"),
            ("at no cost in sensitivity", "sensitivity identity stated as an empirical result"),
            ("no sensitivity cost", "sensitivity identity stated as an empirical result"),
            *ungated_context_view,
        ]
    else:
        tc, forbidden_extra = None, []

    # Stale literals distinctive enough that they cannot legitimately occur
    # anywhere in the paper.
    forbidden_global = [
        ("13 of 16 strong-tier", "stale gating cells (prose)"),
        ("13/16 vs 0/3", "stale gating cells (table)"),
        ("13/17 vs 0/4", "stale sweep row t2.0"),
        ("14/19 vs 0/4", "stale sweep row t1.5"),
        ("15/23 vs 0/6", "stale sweep row t1.0"),
        ("12/15 vs 0/2", "stale sweep row tSAP"),
        ("10/13 against 0/2", "stale residue-collapsed cells"),
        ("tier-only stratum (0.250", "stale tier-only stratum MC"),
        ("adjusted p = 0.052", "stale BH verdict (canonical did not survive)"),
        ("only three survive", "stale BH survivor count"),
        ("a suggestive interaction that this benchmark cannot establish", "stale section title"),
        ("−0.126 to +0.099", "stale AUC delta CI"),
    ]
    # Bare numbers that are stale *here* but legitimate elsewhere -- 0.692, for
    # instance, is a real balanced-MC value in the §3.2 threshold table.
    forbidden_in_section = [
        ("0.562", "stale convergent-stratum MC"),
        ("0.692", "stale convergent-structural MC"),
        ("0.250", "stale tier-only stratum MC"),
    ]

    fsec, ftext = flat(sec), flat(text)
    fails = []

    # The demotion COUNT cannot be audited as a substring: "4 variants" occurs
    # inside "Tier 3-4 variants", so a plain containment test passes even when
    # the prose says three. Parse the number the prose actually states and
    # compare it to the computed list. This is the check that would have caught
    # the original three-vs-four error.
    if tc is not None:
        n_expected = len(tc["all_demotions"])
        WORDS = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
                 "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10}
        m_dem = re.search(r"demotes\s+([A-Za-z]+|\d+)\s+variants", fsec)
        if m_dem is None:
            fails.append(
                "MISSING in §3.12: the ablation sentence no longer states how many "
                f"variants are demoted (expected {n_expected})"
            )
        else:
            tok = m_dem.group(1).lower()
            n_stated = WORDS.get(tok, int(tok) if tok.isdigit() else None)
            if n_stated != n_expected:
                fails.append(
                    f"WRONG COUNT in §3.12: prose says {m_dem.group(1)!r} variants "
                    f"demoted; the ablation demotes {n_expected} "
                    f"({len(tc['structural_demotions'])} structural + "
                    f"{len(tc['silent_demotions'])} silent: "
                    f"{[r['variant'] for r in tc['all_demotions']]})"
                )
    # Boundary-aware matching (see scripts/audit_match.py). Plain containment
    # cannot see prose that overstates precision -- "0.757" sits inside
    # "0.7571" -- and mutation-testing found all 35 digit-ending gates below
    # non-binding before this change. `weak_needle` rejects needles that carry
    # no context to gate ("0", "11"), which must be given surrounding prose.
    for needle, label in required:
        why = weak_needle(needle)
        if why is not None:
            fails.append(f"UNGATEABLE §3.12 check {label!r}: {why}")
        else:
            problem = check_literal(fsec, flat(needle))
            if problem is not None:
                fails.append(f"BAD LITERAL in §3.12: {label!r} -- {problem}")
    for needle, label in forbidden_global + forbidden_extra:
        if flat(needle) in ftext:
            fails.append(f"STALE literal survives in manuscript: {label!r} -- {needle!r}")
    for needle, label in forbidden_in_section:
        if flat(needle) in fsec:
            fails.append(f"STALE literal survives in §3.12: {label!r} -- {needle!r}")

    # --- propagation: the same screen restated OUTSIDE §3.12 ---
    # The section gate above deliberately reads only §3.12, so a headline value
    # copied into the Abstract or Discussion was gated nowhere. No audit read the
    # abstract at all until this block. Needles here carry surrounding prose so a
    # coincidental digit collision with an unrelated quantity (the threshold
    # sweep also produces 0.600, structural agreement also produces 0.757)
    # cannot satisfy them.
    fabs = flat(section(text, "## Abstract", "## 1. Introduction"))
    propagated = [
        (f"{m['specificity']:.3f} specificity", "screen specificity restated in Abstract"),
        (f"all {m['strong_structural']} structurally-mechanistic variants",
         "screen recall restated in Abstract"),
        (f"none of the {m['weak_n']} Tier 3\u20134 variants",
         "screen zero cell restated in Abstract"),
    ]
    for needle, label in propagated:
        why = weak_needle(needle)
        if why is not None:
            fails.append(f"UNGATEABLE Abstract check {label!r}: {why}")
            continue
        problem = check_literal(fabs, flat(needle))
        if problem is not None:
            fails.append(f"BAD LITERAL in Abstract: {label!r} -- {problem}")

    # Structural invariant the prose asserts: the stratified weak cells are
    # subsets of a marginal zero cell. If that ever stops holding, the prose's
    # central argument is wrong even if every number still matches.
    if not m["stratified_cells_are_subsets_of_marginal_zero"]:
        fails.append("INVARIANT BROKEN: stratified weak-tier cells are no longer all zero; "
                     "§3.12's subset argument does not hold and must be rewritten")

    for f in fails:
        print(f"  {f}")
    print(f"\n{len(required)} required literals in §3.12, "
          f"{len(propagated)} propagated into the Abstract, "
          f"{len(forbidden_global) + len(forbidden_in_section) + len(forbidden_extra)} forbidden literals, "
          f"{len(fails)} failure(s)")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
