#!/usr/bin/env python3
"""Fail when a headline value is restated in a document no gate checks.

WHY THIS EXISTS
---------------
Every stale number found in the final audit pass was a DUPLICATE of a value
that lives correctly somewhere else. The paper is gated; its copies were not:

  - figures/README.md mapped superseded PNGs to manuscript figure numbers and
    quoted "mechanism-consistency 0.71, structural agreement 0.76 (92/121)";
  - docs/COMAVI_results_specification.md tabulated 0.7193 and 99/131 as current;
  - docs/design_decisions.md called 0.7193 the "current authoritative headline";
  - docs/COMAVI_current_results.md had a generator that was never re-run, and
    its template hardcoded the fraction while interpolating the computed rate,
    emitting "41/57 = 0.6607" -- a fraction that does not equal its own value.

None of those changed a published result, because the manuscript reads from
reference_outputs. They are a maintenance trap: the next person to grep the
repository for the headline finds four answers.

The rule enforced here is not "no numbers in documents". It is: a value that
this project treats as a headline may appear only where something checks it --
the manuscript source, a generated document, or a file an audit script reads.
Anywhere else, cite the record instead of copying the number.

Usage:
    PYTHONPATH=. python scripts/verify_no_duplicated_headlines.py
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
RO = REPO / "reference_outputs"

# Files allowed to state a headline, each because something checks them.
ALLOWED = {
    "docs/manuscript/COMAVI_manuscript_source.txt":
        "the manuscript itself; build_manuscript.py --check gates it",
    "docs/COMAVI_manuscript_current.txt":
        "generated from the source by extract_manuscript_text.py",
    "docs/COMAVI_current_results.md":
        "generated by build_current_results_summary.py, which asserts its totals",
    "README.md":
        "gated by audit_readme_claims.py",
}
SKIP_DIRS = {".git", "__pycache__", "node_modules", ".pytest_cache", "articles",
             "submission", "reference_outputs", "figures"}
SUFFIXES = {".md", ".txt", ".rst"}


def headline_values() -> dict[str, str]:
    """The tracked values, read from the records rather than typed."""
    sweep = {r["threshold_tag"]: r for r in
             json.loads((RO / "COMAVI_threshold_sweep.json").read_text())["rows"]}
    rub = json.loads((RO / "COMAVI_rubric_baselines.json").read_text())
    nl = json.loads((RO / "COMAVI_numbers_ledger.json").read_text())
    t25 = sweep["t25"]
    out = {
        "%.4f" % t25["whole_variant"]: "COMAVI_threshold_sweep.json rows[t25].whole_variant",
        "%.3f" % t25["whole_variant"]: "COMAVI_threshold_sweep.json rows[t25].whole_variant",
        "%.4f" % rub["baselines"]["never_fire"]["score"]:
            "COMAVI_rubric_baselines.json baselines.never_fire.score",
    }
    sa = nl.get("SA_total")
    if isinstance(sa, (int, float)):
        out["%.4f" % sa] = "COMAVI_numbers_ledger.json SA_total"
    # Superseded headline values: these must never reappear as current claims.
    out.update({
        "0.7193": "SUPERSEDED mechanism-pattern score (pre-v7.9/v8.0)",
        "99/131": "SUPERSEDED structural-agreement fraction",
        "92/121": "SUPERSEDED structural-agreement fraction",
        "92/124": "SUPERSEDED structural-agreement fraction",
        "0.7557": "SUPERSEDED structural agreement",
        "41.0 of 57": "SUPERSEDED mechanism-pattern numerator/denominator",
        "41/57": "SUPERSEDED mechanism-pattern numerator/denominator",
    })
    return out


# Present-tense framings that turn a historical value into a current claim.
CURRENT = re.compile(
    r"\b(?:current(?:ly)?|authoritative|the headline is|headline is now|"
    r"as published|is now)\b", re.I)

# An explicit historical label overrides the present-tense test. A revision log
# legitimately quotes what a value once was, and the surrounding prose often
# contains the word "current" referring to something else entirely -- the first
# version of this gate flagged a line already headed
# "HISTORICAL v7.3 HEADLINE -- superseded by ...".
HISTORICAL = re.compile(
    r"\b(?:historical|superseded|as of THIS revision|at THIS revision|"
    r"formerly|previously|pre-v\d|was\b)", re.I)


def main() -> int:
    tracked = headline_values()
    hits = []
    for path in sorted(REPO.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        rel = str(path.relative_to(REPO))
        if rel in ALLOWED:
            continue
        try:
            text = path.read_text()
        except Exception:
            continue
        for val, where in tracked.items():
            for m in re.finditer(re.escape(val), text):
                window = text[max(0, m.start() - 160):m.end() + 60]
                superseded = where.startswith("SUPERSEDED")
                # A superseded value is a failure only when framed as current;
                # a revision log may legitimately record what it once was.
                if superseded and (HISTORICAL.search(window)
                                   or not CURRENT.search(window)):
                    continue
                hits.append((rel, val, where,
                             re.sub(r"\s+", " ", window)[-130:]))
    if hits:
        print("FAIL: headline values restated in ungated documents (%d)" % len(hits))
        for rel, val, where, ctx in hits[:14]:
            print("  %s: %s" % (rel, val))
            print("      authority: %s" % where)
            print("      ...%s" % ctx)
        print("\n  Cite the record instead of copying the number, or add the file "
              "to ALLOWED with the gate that checks it.")
        return 1
    print("PASS: no tracked headline value is restated in an ungated document "
          "(%d values tracked, %d files allowed)" % (len(tracked), len(ALLOWED)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
